# Generated by Django 5.2.1 on 2025-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_email_not_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
