# Generated by Django 5.2.1 on 2025-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_at_purchase',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(default='Noname', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(default='Noname', max_length=200),
        ),
    ]
