# Generated by Django 5.2.1 on 2025-05-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
